name: equigasto
description: Una aplicación móvil para reparto de gastos similar a Splitwise
publish_to: 'none'
version: 1.0.19+20

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Navigation
  go_router: ^17.0.0

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_sign_in: ^7.2.0
  firebase_messaging: ^16.0.4
  firebase_app_check: ^0.4.1+2
  firebase_remote_config: ^6.1.2
  flutter_local_notifications: ^17.2.1+1
  package_info_plus: ^8.1.1
  
  # Publicidad
  google_mobile_ads: ^6.0.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Utils
  equatable: ^2.0.5
  uuid: ^4.2.1
  intl: ^0.20.2
  share_plus: ^12.0.1
  url_launcher: ^6.3.0
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.0.0
  app_links: ^6.3.1

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "web/icons/Icon-512.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "web/icons/Icon-512.png"
  android_adaptive_icon_background_color: "#FFFFFF"

